# Generated by Django 5.0.2 on 2024-04-20 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='image_description',
            field=models.ImageField(blank=True, upload_to='categories/descriptions'),
        ),
        migrations.AddField(
            model_name='category',
            name='image_list',
            field=models.ImageField(blank=True, upload_to='categories/lists'),
        ),
        migrations.AddField(
            model_name='product',
            name='number_of_rating',
            field=models.IntegerField(default=5, max_length=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='pre_discount_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='rating',
            field=models.IntegerField(default=5, max_length=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='short_description',
            field=models.TextField(blank=True),
        ),
    ]
