# Generated by Django 5.0.2 on 2024-04-21 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_category_image_description_category_image_list_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['-updated']},
        ),
        migrations.RemoveField(
            model_name='category',
            name='image_description',
        ),
        migrations.AddField(
            model_name='product',
            name='image_description',
            field=models.ImageField(blank=True, upload_to='products/descriptions/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='product',
            name='number_of_rating',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='product',
            name='rating',
            field=models.IntegerField(),
        ),
    ]
